#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )
export GOPATH=~/.go

# Set the list of directories that Zsh searches for programs.
path=(
  ~/.go/bin
  /usr/local/opt/go/libexec/bin
  /usr/local/{bin,sbin}
  $path
)

# For vmux

export VMUX_EDITOR=nvim
export VMUX_REALEDITOR_NVIM=/usr/local/bin/nvim
export VMUX_REALEDITOR_VIM=/usr/local/bin/vim
export VMUX_REALEDITOR_GVIM=/usr/local/bin/gvim

#
# Homebrew
#
export HOMEBREW_GITHUB_API_TOKEN="99c07e375a5f12a453b7de071381d324e42aed77"

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

