#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )
export GOPATH=/usr/local/Cellar/go/1.3.1

# Spark ENV
export SPARK_HOME=/usr/local/Cellar/apache-spark/1.6.0/libexec
export PYSPARK_SUBMIT_ARGS="--master local[2]"
# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/Cellar/go/1.3.1/bin
  /Users/niksun/Documents/src/zato-1.1/bin
  /usr/local/mariadb/{bin,sbin}
  /usr/local/{bin,sbin}
  /Library/Frameworks/Mono.framework/Versions/Current/bin
  $path
)

export PKG_CONFIG_PATH=/Library/Frameworks/Mono.framework/External/pkgconfig:/Library/Frameworks/Mono.framework/Versions/Current/lib/pkgconfig:/Library/Frameworks/Mono.framework/Versions/Current/share/pkgconfig:$PKG_CONFIG_PATH

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
