#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export CURL_CA_BUNDLE=~/.ssh/cacert.pem
export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home
export DOCKER_HOST=tcp://172.17.8.150:2375
alias tree="tree|ascii2uni -a K"
alias proxy="proxychains4"
alias douban.fm="douban.fm home /Users/niksun/Music/douban.fm"
alias sl="sl"
alias rm="trash"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export DYLD_LIBRARY_PATH="/usr/local/mariadb/lib"

export WORKON_HOME=$HOME/development/study/python/virtualenvs
source /usr/local/bin/virtualenvwrapper.sh


# for dev
export DEV_DATABASE_URI="mysql://root:12121212@localhost:3306/shop-dev"
export ANDROID_HOME=/usr/local/opt/android-sdk

BASE16_SHELL="$HOME/.config/base16-shell/base16-tomorrow.dark.sh"
[[ -s $BASE16_SHELL  ]] && source $BASE16_SHELL
